### ISSUE TITLE
Refactor a few core modules

### ISSUE THREAD

**Issue by riley-harper** [ipums/hlink#17]
There are a few small refactoring changes that would be good to make in some of the core modules. These are

- [ ] The `id_col` argument to `core.comparison_feature.create_feature_tables()` is not used. Let's get rid of it.
- [ ] The `threshold_ratio` argument to `core.threshold._apply_alpha_threshold()` is also unused, so we can get rid of it too.
- [x] `core.transform` has two `*` imports that make it hard to check for undefined variables. The `pyspark.sql.types` import may be able to go away entirely.

**Comment by jrbalch543** [comment]
Where are the two `*` imports? Working to address this, but am unsure where those are and what the use of that is.
