### ISSUE TITLE
Add support for aliasing columns in only one input dataset

### ISSUE THREAD

**Issue by riley-harper** [ipums/hlink#19]
Right now any `[[column_mappings]]` in the configuration file that alias columns do so for both input datasets at once. It would be nice if you could optionally alias a column from a single dataset. This would allow linking two datasets with similar data whose column names are slightly different.

One workaround for this issue is to rename the columns in the input datasets so that they match, but this is inconvenient.

**Comment by jrbalch543** [comment]
I think I just addressed this in my new PR. Let me know if that looks like a solution.

**Comment by riley-harper** [comment]
While working on implementing this, we discovered some existing features that do this already! They are undocumented, so we made issue #118 to document them. We closed PR #116 in favor of using the existing features instead.
