### ISSUE TITLE
Detect comparison_features with the same output column in config validation

### ISSUE THREAD

**Issue by riley-harper** [ipums/hlink#50]
If two [[comparison_features]] sections share an "alias" or output column, Spark will raise an error due to a duplicate column when it's computing tmp_potential_matches_prepped in matching step 2. We can check for this when we're validating the config file to raise an error much earlier in the process.

A similar check may also apply to other sections like [[feature_selections]] and [[column_mappings]].

**Comment by jrbalch543** [comment]
Ok, so this should be closable now, right?

**Comment by riley-harper** [comment]
Yep, this is done now.

In your PR, if you write "Closes #50" or "Fixes #50" in the description, it will automatically close this issue when the PR is merged. That's a nice way to keep track of closing these issues. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
