### ISSUE TITLE
`JaroWinklerSimilarity` returns 1 for two empty strings

### ISSUE THREAD

**Issue by riley-harper** [ipums/hlink#56]
When we updated Scala Apache Commons Text from 1.4 to 1.9 in version 3.2.0 of hlink, we started using `JaroWinklerSimilarity` instead of `JaroWinklerDistance`. Commons Text renamed `JaroWinklerDistance` to `JaroWinklerSimilarity` because it was actually computing the similarity between two strings. But the behavior on empty strings has also changed, and we didn't notice that until now.

With the new `JaroWinklerSimilarity`, two empty strings `""` and `""` have computed similarity 1.0. This used to be 0.0 with the old `JaroWinklerDistance`. We may need to have a special case to handle this in hlink, as we would like two empty strings to have similarity 0.0.

**Comment by jacwellington** [comment]
I believe all of our Jaro Winkler calls go through [SerJaroWinklerSimilarity](https://github.com/ipums/hlink/blob/465d7ce7882f680a60e5c569d01fd9bf02e8b2f2/scala_jar/src/main/scala/com/isrdi/udfs/SerJaroWinklerSimilarity.scala) . The only method called on SerJaroWinkler is `apply`. We should override the `apply` method to first check if either string is 0 and return 0.0 if true, else call `super.apply()` (or however you do it in Java).

**Comment by riley-harper** [comment]
I think this should do it.

```scala
class SerJaroWinklerSimilarity extends JaroWinklerSimilarity with Serializable {
  override def apply(left: CharSequence, right: CharSequence): Double = {
    if (left == "" && right == "") {
      0.0
    } else {
      super.apply(left, right)
    }
  }
}
```

**Comment by riley-harper** [comment]
Aha, we'll need to specify the return type as `java.lang.Double` so that the function is compatible with Java instead of returning a Scala `Double`.

**Comment by jacwellington** [comment]
We should change the && to an || just to future proof and provide more
short circuiting.

**Comment by riley-harper** [comment]
I'm not sure if switching to `||` will improve short-circuiting or not. If we expect that most calls to `apply()` pass a non-empty string as `left`, then the `&&` will short-circuit out of the `if` in most cases but the `||` will not. The `||` would require evaluating both `==` conditions when `left` is non-empty, but if `right` happens to be empty, then we'll get to skip the method call to `super.apply()`.

If we expect lots of calls to `apply()` with `left` as the empty string, then switching to `||` makes sense to me for sure.
