### ISSUE TITLE
Use colorama more simply

### ISSUE THREAD

**Issue by riley-harper** [ipums/hlink#76]
Recently the colorama package has changed how it handles initialization. Instead of `init()` and `deinit()`, there's now an option to use the `just_fix_windows_console()` function. This function is safe to call multiple times, and we can just call it when the `hlink` script starts up. So let's use `just_fix_windows_console()` once and then not worry about Windows ANSI issues for the rest of the program. Where to call it I'm not quite sure, but it will be nice to be able to get rid of the calls to `init()` and `deinit()`. This will require pinning `colorama>=0.4.6`.

We can still use the colorama `Fore` and `Style` classes to print colored text. There are other packages that also do this, but what we're doing is simple enough that colorama should be fine for now.

**Comment by jrbalch543** [comment]
Just put up a PR for this
